In [ ]:
import numpy as np

In [ ]:
arr=np.array([[12,3,6],
              [4,335,64]])

arr.size
arr.ndim

2

In [ ]:
arr=np.array([[12,3,6],
              [4,335,64]])

arr.sum()
arr.sum(axis=0)
arr.sum(axis=1)

array([ 21, 403])

In [ ]:
arr=np.array([[12,3,6],
              [4,335,64]])

arr.reshape(-1,3)
# arr.reshape(2,2,3)

array([[ 12,   3,   6],
       [  4, 335,  64]])

In [ ]:
arr=np.array([[12,3,6,3,56,78],
              [4,335,64,65,78,97]])

demo=arr.ravel()
# demo[0]=100

arr

array([[ 12,   3,   6,   3,  56,  78],
       [  4, 335,  64,  65,  78,  97]])

In [ ]:
arr = np.array([12,3,6,4,33,64,54,82,84,2,98,87])

k = arr.reshape(3,4)

arr[0] = 100

print(k)

[[100   3   6   4]
 [ 33  64  54  82]
 [ 84   2  98  87]]


In [ ]:
arr = np.array([12,3,6,4,33,64,54,82,84,2,98,87])

k = arr.reshape(3,4).copy()

print(arr[0])
print(k)

12
[[12  3  6  4]
 [33 64 54 82]
 [84  2 98 87]]


In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np

In [ ]:
d = np.array([100,23,45,67,89,98,87,65,43,32,56,78])

print(d * 3)

[300  69 135 201 267 294 261 195 129  96 168 234]


In [ ]:
n = [5,6,7]

print(n * 3)

[5, 6, 7, 5, 6, 7, 5, 6, 7]


In [ ]:
d = np.array([100,23,45,67,89,98,87,65,43,32,56,78])

mask = (d > 80)

print(mask)
print(d[mask])
print(d[~mask])

[ True False False False  True  True  True False False False False False]
[100  89  98  87]
[23 45 67 65 43 32 56 78]


In [ ]:
d = np.array([100,23,45,67,89,98,87,65,43,32,56,78])

a = (d > 70) & (d < 90)

print(d[a])

[89 87 78]


In [ ]:
print(np.where(d > 70))

(array([ 0,  4,  5,  6, 11]),)


In [ ]:
cond = [
    ((d >= 40) & (d <= 75)),
    ((d > 75) & (d <= 100))
]

choice = ["Small", "Medium"]

print(np.select(cond, choice, default="Large"))

['Medium' 'Large' 'Small' 'Small' 'Medium' 'Medium' 'Medium' 'Small'
 'Small' 'Large' 'Small' 'Medium']


In [ ]:
m = (d % 2 == 0) | (d % 5 == 0) | (d % 7 == 0)

data = d[~m]

print(data)

[23 67 89 87 43]
